// Cooked-to-raw yield factors: cooked weight = raw weight × factor.
// Typical/average values — editable per-use in the converter via the factor box.

export const YIELDS = [
  { name: 'Chicken breast', factor: 0.71 },
  { name: 'Chicken thigh', factor: 0.70 },
  { name: 'Ground beef (85/15)', factor: 0.73 },
  { name: 'Ground beef (93/7)', factor: 0.76 },
  { name: 'Ground turkey', factor: 0.74 },
  { name: 'Steak (beef)', factor: 0.70 },
  { name: 'Pork chop', factor: 0.72 },
  { name: 'Pork tenderloin', factor: 0.75 },
  { name: 'Bacon', factor: 0.35 },
  { name: 'Salmon', factor: 0.77 },
  { name: 'White fish (cod, tilapia)', factor: 0.78 },
  { name: 'Shrimp', factor: 0.75 },
  { name: 'Eggs (scrambled)', factor: 0.90 },
  { name: 'White rice', factor: 2.95 },
  { name: 'Brown rice', factor: 2.80 },
  { name: 'Jasmine rice', factor: 2.90 },
  { name: 'Quinoa', factor: 2.75 },
  { name: 'Pasta', factor: 2.25 },
  { name: 'Oats (with water)', factor: 2.50 },
  { name: 'Lentils (dry)', factor: 2.50 },
  { name: 'Beans (dry)', factor: 2.30 },
  { name: 'Potatoes (baked)', factor: 0.81 },
  { name: 'Potatoes (boiled)', factor: 0.97 },
  { name: 'Sweet potato (baked)', factor: 0.80 },
  { name: 'Vegetables (roasted)', factor: 0.80 },
  { name: 'Vegetables (steamed)', factor: 0.90 },
  { name: 'Mushrooms (sautéed)', factor: 0.55 },
  { name: 'Spinach (cooked)', factor: 0.30 },
  { name: 'Onions (caramelized)', factor: 0.45 },
];
